import { PrismaClient } from "@prisma/client";
import { SQLDatabase } from "encore.dev/storage/sqldb";

/**
 * An SQL database named ' ', using the database migrations
 * in the "./prisma/migrations" folder (where prisma will generate their migrations).
 * Set `source` to `prisma` to let Encore know that the migrations are generated by db.
 */
const database = new SQLDatabase("encore_prisma_test", {
	migrations: {
		path: "./prisma/migrations",
		source: "prisma",
	},
});

/**
 * A Prisma client for the database.
 */
export const db = new PrismaClient({
	datasources: {
		db: {
			url: database.connectionString,
		},
	},
});
